# Generated by Django 3.2.4 on 2021-06-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=255, verbose_name='Новости')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.FileField(blank=True, upload_to='announcement_image/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=100, verbose_name='Клуб')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('seat', models.PositiveSmallIntegerField(verbose_name='Мест')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='ClubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='club_images', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='ClubRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_rules', models.CharField(max_length=255, verbose_name='Название правила клуба')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
            },
        ),
        migrations.CreateModel(
            name='ComputerClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_club', models.CharField(max_length=100, verbose_name='Компьютерные клубы')),
            ],
            options={
                'verbose_name': 'Компьютерный клуб',
                'verbose_name_plural': 'Компьютерные клубы',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=255, verbose_name='Название игры')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GameAccessoriesSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_accessories_specification', models.CharField(max_length=255, verbose_name='Девайс')),
                ('text', models.TextField(verbose_name='Описание характеристики девайса')),
            ],
            options={
                'verbose_name': 'Девайс',
                'verbose_name_plural': 'Девайсы',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='price_list_images', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Прайс лист',
                'verbose_name_plural': 'Прайс листы',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_number', models.IntegerField(verbose_name='Номер места')),
                ('status', models.IntegerField(choices=[(1, 'Свободно'), (2, 'Занято'), (3, 'В данный момент компьютер находится на тех-обслуживании')], default=1, verbose_name='Статус')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_table', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default='00:00')),
                ('using_time', models.FloatField(default='00:00')),
                ('status', models.IntegerField(choices=[(1, 'Свободно'), (2, 'Занято'), (3, 'В данный момент компьютер находится на тех-обслуживании')], default=2, verbose_name='Статус')),
                ('computer_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_reservation', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
            },
        ),
    ]
