# Generated by Django 3.2.4 on 2021-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='00:00', verbose_name='Введите время бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='using_time',
            field=models.PositiveSmallIntegerField(verbose_name='Введите на сколько часов вы садитесь'),
        ),
    ]
