# Generated by Django 3.2.4 on 2021-07-08 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20210703_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(verbose_name='Введите время бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='using_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Меньше 1 нельзя!'), django.core.validators.MaxValueValidator(10, message='Больше 10 нельзя!')], verbose_name='Введите на сколько часов вы садитесь'),
        ),
    ]
